services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "11802:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

volumes:
  mongodata: